version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - Resonaa
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    reviewers:
      - Resonaa
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - Resonaa
    groups:
      all:
        patterns:
          - "*"
