repos:
  - repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
      - id: committed

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/crate-ci/typos
    rev: v1.24.5
    hooks:
      - id: typos
        args: []

  - repo: local
    hooks:
      - id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        files: none
        always_run: true

      - id: rustfmt
        name: rustfmt
        entry: cargo +nightly fmt
        language: system
        files: none
        always_run: true

      - id: doc
        name: doc
        entry: cargo doc --no-deps
        language: system
        files: none
        always_run: true
