blank_issues_enabled: true
contact_links:
  - name: Ask a question
    about: |
      You've come to seek help or want to discuss something related to gfas.
    url: https://github.com/Resonaa/gfas/discussions/new
