name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dev Build
        run: cargo build --verbose

      - name: Release Build
        run: cargo build --release --verbose

      - name: Doc
        run: cargo doc --no-deps --lib
