name: Auto Version Bump

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    name: Bump Patch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Log in to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Install jq
        run: sudo apt install jq
      - name: Get owner info
        shell: bash
        run: |
          USER_INFO=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/user)
          USER_EMAIL=$(echo "$USER_INFO" | jq -r ".email")
          echo "GIT_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
      - name: Setup git
        run: |
          echo ${{ secrets.TOKEN }} | gh auth login --with-token
          gh auth setup-git
          git config --local user.email ${{ env.GIT_EMAIL }}
          git config --local user.name ${{ github.repository_owner }}
          git add .
      - name: Patch release
        run: cargo release patch --workspace --no-verify --no-confirm --no-push --execute
      - name: Push
        run: gh repo sync
