name: Auto Version Bump

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    name: Bump Patch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Log in to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Setup git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
      - name: Patch release
        run: cargo release patch --workspace --no-verify --no-confirm --execute
      - name: Trigger release workflow
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(grep 'version =' ./crates/gfas-api/Cargo.toml | sed 's/.*version = "\(.*\)".*/\1/')
          gh workflow run release.yml --ref v$VERSION
