name: CI

on:
  push:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rust-docs --no-self-update
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Doc
        run: cargo doc --no-deps

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --component clippy --no-self-update
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install nightly --profile minimal --component rustfmt --no-self-update
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo +nightly fmt
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "chore: format"
          git push

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Coverage
        run: cargo tarpaulin --output-dir coverage --out xml --workspace
      - name: Upload
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/cobertura.xml
