name: Pre-commit Auto Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pre-commit
        uses: threeal/pipx-install-action@v2
        with:
          packages: pre-commit
      - name: Print pre-commit version
        run: pre-commit --version
      - name: Update pre-commit config
        run: pre-commit autoupdate
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "chore(deps): update pre-commit config "
          git push
